# Generated by Django 5.2.17 on 2026-09-24 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: 7А", max_length=20, verbose_name="Класс"
                    ),
                ),
                (
                    "grade",
                    models.PositiveSmallIntegerField(
                        default=7, verbose_name="Параллель"
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        default="2026-2027", max_length=9, verbose_name="Учебный год"
                    ),
                ),
            ],
            options={
                "verbose_name": "Класс",
                "verbose_name_plural": "Классы",
                "ordering": ["grade", "name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Тема урока")),
                ("date", models.DateField(blank=True, null=True, verbose_name="Дата")),
                (
                    "duration_min",
                    models.PositiveSmallIntegerField(
                        default=45, verbose_name="Длительность, мин"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("kk", "Қазақша"),
                            ("en", "English"),
                        ],
                        default="ru",
                        max_length=2,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Что учесть при генерации",
                        verbose_name="Пожелания для AI",
                    ),
                ),
                ("objectives", models.TextField(blank=True, verbose_name="Цели урока")),
                ("plan", models.TextField(blank=True, verbose_name="План урока")),
                (
                    "key_points",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Ключевые тезисы (для видео)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("ready", "Готов"),
                            ("done", "Проведён"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        upload_to="videos/",
                        verbose_name="Видео (Hyperframes)",
                    ),
                ),
                (
                    "video_status",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Статус видео"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.classroom",
                        verbose_name="Класс",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="school.subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("quiz", "Тест"),
                            ("homework", "Домашнее задание"),
                            ("essay", "Эссе"),
                        ],
                        default="quiz",
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                ("content", models.TextField(verbose_name="Условие / вопросы")),
                (
                    "answer_key",
                    models.TextField(blank=True, verbose_name="Ответы / критерии"),
                ),
                (
                    "max_score",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="Макс. балл"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Срок сдачи"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="school.lesson",
                        verbose_name="Урок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задание",
                "verbose_name_plural": "Задания",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150, verbose_name="ФИО")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="school.classroom",
                        verbose_name="Класс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ученик",
                "verbose_name_plural": "Ученики",
                "ordering": ["classroom", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(verbose_name="Ответ ученика")),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Балл"
                    ),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "ai_checked",
                    models.BooleanField(default=False, verbose_name="Проверено AI"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Сдано"),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="school.assignment",
                        verbose_name="Задание",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ ученика",
                "verbose_name_plural": "Ответы учеников",
                "unique_together": {("assignment", "student")},
            },
        ),
    ]
